name: Trigger Update Queue
on:
  schedule:
    - cron: '*/11 * * * *'
jobs:
  build:
    name: Trigger Update
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X POST -d {} https://leetcoder.vercel.app/api/update/queue?limit=3&age=3600
